export type QUEST_TYPE = "DAILY" | "TASK";

export type QUEST_REQUEST_TYPE =
  | "CHECK_IN_TON_WALLET"
  | "PLAY_CAT_BATTLE"
  | "INVITE"
  | "VISIT_PLAYS_COMMUNITY"
  | "VISIT_OFFICIAL_WEBSITE"
  | "CONNECT_TON_WALLET"
  | "JOIN_PLAYS_CHANNEL"
  | "JOIN_PLAYS_CHAT"
  | "FOLLOW_PLAYS_ON_X"
  | "COMPLETE_DAILY_TASK"
  | "COMPLETE_DAILY_TASK";
